apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- operator/namespace.yaml
- instance/rbac.yaml
- instance/argo-crd.yaml
- operator/gitops-operator-subscription.yaml
- instance/application-project.yaml
- instance/application-set.yaml

patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: ApplicationSet
    name: cluster-base
    namespace: openshift-gitops
  path: patch-overlay.yaml