apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: application-project
  namespace: application-argocd
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    app.kubernetes.io/instance: application-argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Application configuration
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - ''