kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-application-controller-additional
  labels:
    app.kubernetes.io/instance: application-argocd
rules:
- verbs:
    - '*'
  apiGroups:
    - "apiextensions.k8s.io"
  resources:
    - customresourcedefinitions
- verbs:
    - '*'
  apiGroups:
    - "apps"
  resources:
    - statefulsets
- verbs:
    - '*'
  apiGroups:
    - "networking.k8s.io"
  resources:
    - networkpolicies
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-controller-additional-rbac
  labels:
    app.kubernetes.io/instance: application-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller-additional
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops