apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: apicast
  namespace: openshift-3scale
spec:
  replicas: 1
  selector:
    deploymentconfig: apicast
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: apicast
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9421'
    spec:
      containers:
      - env:
        - name: THREESCALE_PORTAL_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: apicast-configuration-url-secret
              key: password
        - name: THREESCALE_CONFIG_FILE
          value: 
        - name: THREESCALE_DEPLOYMENT_ENV
          value: production
        - name: RESOLVER
          value: ""
        - name: APICAST_SERVICES_LIST
          value: ""
        - name: APICAST_CONFIGURATION_LOADER
          value: boot
        - name: APICAST_PATH_ROUTING
          value: False
        - name: APICAST_RESPONSE_CODES
          value: False
        - name: APICAST_CONFIGURATION_CACHE
          value: ""
        - name: APICAST_MANAGEMENT_API
          value: status
        - name: OPENSSL_VERIFY
          value: False
        image: "registry.redhat.io/3scale-amp2/apicast-gateway-rhel8:3scale2.10"
        imagePullPolicy: IfNotPresent
        name: apicast
        livenessProbe:
          httpGet:
            path: /status/live
            port: management
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /status/ready
            port: management
          initialDelaySeconds: 15
          timeoutSeconds: 1
        ports:
        - name: proxy
          containerPort: 8080
          protocol: TCP
        - name: management
          containerPort: 8090
          protocol: TCP
        - name: metrics
          containerPort: 9421
          protocol: TCP
        resources:
          limits:
              cpu: '1'
              memory: 128Mi
          requests:
              cpu: 500m
              memory: 64Mi
  triggers:
  - type: ConfigChange