apiVersion: v1
kind: DeploymentConfig
metadata:
  name: apicast
spec:
  replicas: 1
  selector:
    deploymentconfig: apicast
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        deploymentconfig: apicast
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9421'
    spec:
      containers:
      - env:
        name: apicast
        livenessProbe:
          httpGet:
            path: /status/live
            port: management
          initialDelaySeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /status/ready
            port: management
          initialDelaySeconds: 15
          timeoutSeconds: 1
        ports:
        - name: proxy
          containerPort: 8080
          protocol: TCP
        - name: management
          containerPort: 8090
          protocol: TCP
        - name: metrics
          containerPort: 9421
          protocol: TCP
        resources:
          limits:
              cpu: '1'
              memory: 128Mi
          requests:
              cpu: 500m
              memory: 64Mi
  triggers:
  - type: ConfigChange
---
kind: Service
apiVersion: v1
metadata:
  name: apicast
  namespace: openshift-3scale
  labels:
    app: 3scale-api-management
spec:
  ports:
    - name: gateway
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: management
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
    selector:
      deploymentconfig: