kind: Service
apiVersion: v1
metadata:
  name: apicast
  namespace: openshift-3scale
  labels:
    app: 3scale-api-management
spec:
  ports:
    - name: gateway
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: management
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    deploymentconfig: apicast