apiVersion: v1
imagePullSecrets:
- name: threescale-registry-auth
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: zync-que-sa
  namespace: openshift-3scale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: zync-que-rolebinding
  namespace: openshift-3scale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zync-que-role
subjects:
- kind: ServiceAccount
  name: zync-que-sa