apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- operator/namespace.yaml
- operator/operatorgroup.yaml
- operator/subscription.yaml
- instance/apimanager.yaml
- instance/apicast.yaml
- instance/zync-cm.yaml
- instance/zync-rbac.yaml
- instance/zync.yaml